Fix moloch PCAP download functionality  (#6)
* rename helm to moloch

* Jenkinsfile update

* Update Jenkinsfile

* Jenkins tests

* Added 'capture' to Jenkins queries for worker nodes

* typo

* Give Moloch another minute to start

* Added run as user security context

* revert user changes

* changes for new style of ingress

- works with "moloch.FQDN" now instead of "FQDN/moloch"

* comment out building of the image

* helm lint fix

* change

* no custom image

* remove custom values

* tone down sleep time

* nodes now run viewers

* update container files

* open ports for the capture

* forgot the ports line

* fix role

* testing

* revert changes

* experiment

* forgot the search

* update

* fix

* typo

* fix env variable

* sed instead of echo

* test fix

* forgot the &&'s

* changes

* test changes

* fix env var

* update container files

* don't really need a hostpath for logs

* secrets for interface names

* add host networking

* fixes

* writable config

* test cchanges

* fix attempt

* dnsConfig testing

* fix

* network fixes, changed pullpolicy

* update container files + viewer & capture yamls

* Update moloch/templates/moloch-ingress.yaml

* uniform settings structure

* update container script

* update image

* updates to fix pcap download feature

* add pod_name env variable

* update README

diff --git a/moloch/templates/moloch-capture.yaml b/moloch/templates/moloch-capture.yaml
--- a/moloch/templates/moloch-capture.yaml
+++ b/moloch/templates/moloch-capture.yaml
@@ -22,14 +22,36 @@ spec:
         role: capture
       annotations:
         networks: '[
+        {{- if ne .Values.networks.useHostNeworking true }}
         { "name": {{ .Values.networks.overlay | quote }} },
         { "name": {{ .Values.networks.passive | quote }} }
+        {{- else }}
+        { "name": {{ .Values.networks.overlay | quote }} }
+        {{- end }}
       ]'
     spec:
+      initContainers:
+      - name: verifynode
+        image: {{ .Values.images.runner }}
+        env:
+        - name: INTERFACE
+          valueFrom:
+            secretKeyRef:
+              name: passive-interface
+              key: interface
+        - name: STARTUP_SCRIPT
+          value: |
+            #!/bin/bash
+            set -e
+            sleep 10
+            if [ ! -f /sys/class/net/$INTERFACE/operstate ]; then
+            echo "Network interface '$INTERFACE' not found, exiting..."
+            exit 1
+            fi
       containers:
       - name: moloch-capture
         image: {{ .Values.images.moloch }}
-        command: ["bash","-c","cp /etc/resolv.conf /etc/resolv2.conf && sed -i 's/search /search {{ template "moloch.fullname" . }}-headless.'$NAMESPACE'.svc.cluster.local /' /etc/resolv2.conf && cp /etc/resolv2.conf /etc/resolv.conf && /data/moloch/docker-entrypoint.sh"]
+        command: ["bash", "-c", "yes | cp /tmp/moloch/config.ini /data/moloch/etc/config.ini && /data/moloch/docker-entrypoint.sh"]
         imagePullPolicy: Always
         securityContext:
           capabilities:
@@ -44,14 +66,21 @@ spec:
               fieldPath: metadata.namespace
         - name: ES_HOST
           value: data-service
-        - name: NETWORK_INTERFACE
-          value: {{ .Values.networks.passive }}
         - name: CLUSTER_PW
           value: {{ .Values.molochConfig.env.clusterpw }}
         - name: ADMIN_PW
           value: {{ .Values.molochConfig.env.adminpw }}
         - name: SENSOR
           value: "true"
+        - name: INTERFACE
+          valueFrom:
+            secretKeyRef:
+              name: passive-interface
+              key: interface
+        - name: POD_NAME
+          valueFrom:
+            fieldRef:
+              fieldPath: metadata.name
         ports:
         - name: cport-8005
           containerPort: 8005
@@ -63,25 +92,26 @@ spec:
             cpu: {{ .Values.molochConfig.limits.cpu | quote }}
             memory: {{ .Values.molochConfig.limits.memory | quote }}
         volumeMounts:
-        - mountPath: /data/moloch/logs
-          name: molochlogs
         - mountPath: /data/moloch/raw
           name: molochraw
-        - mountPath: /data/moloch/etc/config.ini
+        - mountPath: /tmp/moloch/config.ini
           subPath: config.ini
           name: moloch-config
 
       volumes:
-      - name: molochlogs
-        hostPath:
-          path: {{ .Values.volumes.logs }}
       - name: molochraw
         hostPath:
           path: {{ .Values.volumes.raw }}
       - name: moloch-config
         configMap:
-          name: {{ template "moloch.fullname" . }}-config 
+          name: {{ template "moloch.fullname" . }}-config   
       restartPolicy: Always
-      dnsPolicy: ClusterFirst
+      {{- if .Values.networks.useHostNeworking }}
+      hostNetwork: true
+      dnsPolicy: ClusterFirstWithHostNet
+      {{- end }}
+      dnsConfig:
+        searches:
+          - {{ template "moloch.fullname" . }}-headless.{{ .Release.Namespace }}.svc.cluster.local
       nodeSelector:
         {{ .Values.nodeSelector.worker }} : "true"
